### ISSUE TITLE
Any specific reason for the magic number chosen?

### ISSUE THREAD

**Issue by mousetail** [BiagioFesta/EvolutionNet#2]
The magic number in the save format, `03 bf 0e bf` seems arbitrary. Is there any reason this specific number was chosen?

**Comment by BiagioFesta** [comment]
Not really. As the number suggest, that's magic number that aims to identify the format of the binary file (even if not really needed).

https://en.wikipedia.org/wiki/File_format#Magic_number

**Comment by mousetail** [comment]
I know but usually the magic number is some string in ASCII, like `�PNG` for PNG. That clarifies though thanks.

Also thanks for the library it's helpful

**Comment by BiagioFesta** [comment]
Not really, at least not entirely.
https://en.wikipedia.org/wiki/List_of_file_signatures

Some common extensions have a mix of bytes that have a printable ASCII representation and not

Thank you, and appreciate the feedback! :)
